spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    data-username: root
    data-password: root
  profiles:
    active: @profile.active@
server:
  servlet:
    context-path: /spring-sqlite
mybatis:
  mapper-locations: cn.letcafe.mapper.*